
name: Triggered by the creation of a pull request

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  train:
    runs-on: debian-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"
  
