
name: Triggered by the creation of a pull request

on:
  pull_request:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"
  
