name: dev-prod-run

on:
  push:
    branches: [ main ]

jobs:
  job1:
    name: experiment
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: run dev ML job
      run: |
        az ml job create --file src/job.yml --resource-group Azure-ML --workspace-name AzML --stream
  job2:
    name: production
    runs-on: ubuntu-latest
    environment: production
    needs: job1
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: run prod ML job
      run: |
        az ml job create --file src/job-prod.yml --resource-group Azure-ML --workspace-name AzML
